environments:
  prod:
    variables:
      - name: CURL_TLS_FLAGS
        value: ''
  dev:
    variables:
      - name: HOST
        value: docker

      - name: DOMAIN
        value: pukiru.online
      - name: TRAEFIK_IMAGE_TAG
        value: "traefik:v3.6.7"

      - name: TRAEFIK_LOG_LEVEL
        value: WARN

      - name: TRAEFIK_ACME_EMAIL
        value: dalton@pukiru.games

      - name: TRAEFIK_BASIC_AUTH
        value: "test:$2y$10$leXJg98mfBd6W4.oZ76xd.0OFkLIb3nEYFwZoR.Oj//iUHEw9I15G"

      - name: TRAEFIK_ACME_dns_api_secret
        value:
          bitwarden:
            entry: pukiru-online-cloudflare_dns_secret
            field: login.password

      - name: TRAEFIK_DASHBOARD_ROUTE_PREFIX
        value: traefik

      - name: VAULTWARDEN_IMAGE_TAG
        value: "vaultwarden/server:latest"

      - name: VAULTWARDEN_ADMIN_TOKEN
        value: "$argon2id$v=19$m=65540,t=3,p=4$865qZ/LHDyNs7g/2LyiEAuZ9Sg/4/qc/FOICBhIUWIk$DoCoRjQ/ra1wsE+FencycCoFmMkkl4zLzuWYiir/I70"

      - name: VAULTWARDEN_SIGNUPS_ALLOWED
        value: "true"

      - name: VAULTWARDEN_ROUTE_PREFIX
        value: vault

      - name: SMTP_HOST
        value: mail.smtp2go.com

      - name: SMTP_PORT
        value: "2525"

      - name: SMTP_SECURITY
        value: starttls

      - name: VAULTWARDEN_SMTP_FROM
        value: vault@pukiru.online

      - name: SMTP_USERNAME
        value:
          bitwarden:
            entry: pukiru-online-smtp2go
            field: login.username

      - name: SMTP_PASSWORD
        value:
          bitwarden:
            entry: pukiru-online-smtp2go
            field: login.password

      - name: KEYCLOAK_POSTGRES_IMAGE_TAG
        value: "postgres:17.7"

      - name: KEYCLOAK_POSTGRES_DB
        value: "keycloak_db"

      - name: KEYCLOAK_POSTGRES_USER
        value:
          bitwarden:
            entry: pukiru-online-keycloak_postgres_user
            field: login.username

      - name: KEYCLOAK_POSTGRES_PASSWORD
        value:
          bitwarden:
            entry: pukiru-online-keycloak_postgres_user
            field: login.password

      - name: KEYCLOAK_IMAGE_TAG
        value: "quay.io/keycloak/keycloak:26.4"

      - name: KEYCLOAK_ADMIN
        value:
          bitwarden:
            entry: pukiru-online-keycloak_admin
            field: login.username

      - name: KEYCLOAK_ADMIN_PASSWORD
        value:
          bitwarden:
            entry: pukiru-online-keycloak_admin
            field: login.password

      - name: KEYCLOAK_ROUTE_PREFIX
        value: auth

      - name: KEYCLOAK_REALM_NAME
        value: pukiru_online

      - name: OAUTH_COOKIE_SECRET
        value:
          bitwarden:
            entry: pukiru-online-oauth_cookie_secret
            field: login.password

      - name: APPLICATION_ID
        value: whoami

      - name: APPLICATION_CLIENT_SECRET
        value:
          bitwarden:
            entry: pukiru-online-oauth2_proxy_client_secret
            field: login.password
