environments:
  dev:
    variables:
      - name: SMTP_USERNAME
        value:
          bitwarden:
            entry: scriptkitties-club-smtp2go
            field: login.username

      - name: SMTP_PASSWORD
        value:
          bitwarden:
            entry: scriptkitties-club-smtp2go
            field: login.password
