secrets:
  whoami_oauth_cookie_secret:
    file: ${OAUTH_SECRETS_DIR}/whoami_oauth_cookie_secret.txt
  whoami_application_client_secret:
    file: ${OAUTH_SECRETS_DIR}/whoami_application_client_secret.txt
services:
  whoami_proxy:
    extends:
      file: ../auth/proxy/compose.oauth2_proxy_base.yaml
      service: oauth2_proxy_base
    secrets:
      - whoami_oauth_cookie_secret
      - whoami_application_client_secret
    environment:
      APPLICATION_ID: whoami
      OAUTH_COOKIE_SECRET_FILE: /run/secrets/whoami_oauth_cookie_secret
      APPLICATION_CLIENT_SECRET: /run/secrets/whoami_application_client_secret
      REDIRECT_URL: "https://${HOST}.${DOMAIN}/whoami"
#      OIDC_ISSUER_URL: "https://${HOST}.${DOMAIN}/${KEYCLOAK_ROUTE_PREFIX}/realms/${KEYCLOAK_REALM}"
#      EMAIL_DOMAIN: "*"
  whoami:
    extends:
      file: common.yaml
      service: application
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${HOST}.${DOMAIN}`)&&PathRegexp(`^/whoami/?`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # Apply middlewares
      - "traefik.http.routers.whoami.middlewares=compress-traefik@file,oauth-auth,oauth-errors,security-headers@file"
      # Enable TLS on this router
      - "traefik.http.routers.whoami.tls=true"
#      # Use Let's Encrypt for TLS management
#      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
