secrets:
  whoami_oauth_cookie_secret:
    file: ${OAUTH_CONFIG_DIR}/whoami/oauth_cookie_secret
  whoami_oauth_client_secret:
    file: ${OAUTH_CONFIG_DIR}/whoami/oauth_client_secret
services:
  whoami-oauth2-proxy:
    hostname: oauth2-proxy-whoami
    extends:
      file: ../auth/proxy/compose.oauth2_proxy_base.yaml
      service: oauth2-proxy-base
    secrets:
      - whoami_oauth_cookie_secret
      - whoami_oauth_client_secret
    labels:
      - "traefik.http.routers.whoami-oauth2-proxy.service=whoami-oauth2-proxy"
      - "traefik.http.services.whoami-oauth2-proxy.loadbalancer.server.port=4180"
      - "traefik.http.services.whoami-oauth2-proxy.loadbalancer.passhostheader=true"
    volumes:
      - "${OAUTH_CONFIG_DIR}/whoami/oauth2-proxy.cfg:/oauth2-proxy.cfg"
  whoami:
    extends:
      file: common.yaml
      service: application
    image: traefik/whoami
    depends_on:
      whoami-oauth2-proxy:
        condition: service_healthy
    labels:
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"
