secrets:
  whoami-admin_oauth_cookie_secret:
    file: ${OAUTH_CONFIG_DIR}/whoami-admin/oauth_cookie_secret
  whoami-admin_oauth_client_secret:
    file: ${OAUTH_CONFIG_DIR}/whoami-admin/oauth_client_secret
services:
  whoami-admin-oauth2-proxy:
    hostname: oauth2-proxy-whoami-admin
    extends:
      file: ../auth/proxy/compose.oauth2_proxy_base.yaml
      service: oauth2-proxy-base
    secrets:
      - whoami-admin_oauth_cookie_secret
      - whoami-admin_oauth_client_secret
    labels:
      - "traefik.http.routers.whoami-admin-oauth2-proxy.service=whoami-admin-oauth2-proxy"
      - "traefik.http.services.whoami-admin-oauth2-proxy.loadbalancer.server.port=4180"
      - "traefik.http.services.whoami-admin-oauth2-proxy.loadbalancer.passhostheader=true"
    volumes:
      - "${OAUTH_CONFIG_DIR}/whoami-admin/oauth2-proxy.cfg:/oauth2-proxy.cfg"
  whoami-admin:
    extends:
      file: common.yaml
      service: application
    image: traefik/whoami
    depends_on:
      whoami-admin-oauth2-proxy:
        condition: service_healthy
    labels:
      - "traefik.http.routers.whoami-admin.service=whoami-admin"
      - "traefik.http.services.whoami-admin.loadbalancer.server.port=80"
      - "traefik.http.services.whoami-admin.loadbalancer.passhostheader=true"